angular.module('mapp')
	.config(function($stateProvider,$urlRouterProvider){
		$urlRouterProvider.otherwise('/guide');
		$stateProvider
			.state('guide',{
				url:'/guide',
				templateUrl:'./tpl/guide.html',
				controller:'guideCtrl'
			})
			.state('app',{
				url:'/app',
				templateUrl:'./tpl/app.html'
			})
			.state('app.search',{
				url:'/search',
				templateUrl:'./tpl/search.html'
			})
			.state('app.my',{
				url:'/my',
				templateUrl:'./tpl/my.html'
			})
			.state('app.exit',{
				url:'/exit',
				templateUrl:'./tpl/exit.html'
			})
			.state('app.home',{
				url:'/home',
				templateUrl:'./tpl/home.html',
				controller:'homeCtrl'
			})
	})