angular.module('mapp')
	.config(function($stateProvider,$urlRouterProvider){
		$urlRouterProvider.otherwise('/guide');
		$stateProvider
			.state('guide',{
				url:'/guide',
				templateUrl:'./src/scripts/tpl/guide.string',
				controller:'guideCtrl'
			})
			.state('app',{
				url:'/app',
				templateUrl:'./src/scripts/tpl/app.string'
			})
			.state('app.search',{
				url:'/search',
				templateUrl:'./src/scripts/tpl/search.string'
			})
			.state('app.my',{
				url:'/my',
				templateUrl:'./src/scripts/tpl/my.string'
			})
			.state('app.exit',{
				url:'/exit',
				templateUrl:'./src/scripts/tpl/exit.string'
			})
			.state('app.home',{
				url:'/home',
				templateUrl:'./src/scripts/tpl/home.string',
				controller:'homeCtrl'
			})
	})